Make blog link unique
MovingBlocks/movingblocks.github.com pull request #242
Opened 2024-04-23 18:48 UTC by 5archoufa

Include date in URL

2024-05-02 12:36 UTC, jdrueckert requested changes
From looking at the code changes (and ignoring the ones duplicating #239), this looks reasonable. I'll need to test it, though, before merging. I'll try to find time to do that this weekend, not sure I will though, so apologies as it might take another week before I get to merge this.

Meanwhile please remove the unused var declaration in `Blog.jsx` and the changes duplicating your other PR.

2024-05-02 12:36 UTC, jdrueckert commented on src/templates/Blog.jsx
> +
as you're not referencing `codeBlockRegex` anywhere, I assume this can be removed

2024-05-08 13:03 UTC, jdrueckert commented
Locally tested this and noticed two issues:

1. I don't think we need the entire date and timestamp in the blog link. Currently it's unlikely that we even write two blog posts in a month... Using the date should be enough even if the website picks up in blogs written again in the future.
2. The blog preview cards on the front page don't properly navigate to the correct post when clicking on "Read more". Seems like they still use the "old" (not unique) links.

2024-05-11 18:01 UTC, Rukki13 commented
I've made a pull request here: #244

2024-05-11 18:01 UTC, Rukki13 commented
you can close the older one (#242)

2024-05-15 19:13 UTC, jdrueckert commented
> I've made a pull request here: #244

Okay, then I'll close this one. But, just fyi, you don't need to open a new PR whenever you add changes. You can simply push to the same branch again and the PR should update.

2024-05-15 19:13 UTC, closed without merging