Ft/gc/about
MovingBlocks/movingblocks.github.com pull request #26
Opened 2019-10-09 23:29 UTC by GraceChiamaka

### What will this PR do
This PR would add the about component

2019-10-09 23:30 UTC, GraceChiamaka commented
@majordwarf please review

2019-10-10 04:17 UTC, Cervator commented
Thanks @GraceChiamaka :-)

Would you mind expanding a bit on your description? I take it this is drawing in content from the existing site repo powering terasology.org ? Have you made any particular modifications to make stuff work well? Have you tested the updates and if so do you have either a preview URL or a screenshot or two? That'll all help 👍

2019-10-10 06:38 UTC, majordwarf requested changes
On a sidenote, please use `reactstrap` that will help avoid writing `className` attribute again and again, providing a much better readability and only focuses on the user-defined classes.

2019-10-10 06:38 UTC, majordwarf commented on src/components/About/About.jsx
> +              </p>
Same as above the content doesn't highlight any Modding API stuff, also no need to go technical here. Better change the topic to `Modular` rather than `Modding API` and edit the content accordingly.

2019-10-10 06:38 UTC, majordwarf commented on src/components/About/About.jsx
> +              for modules and game extensions from anyone and everyone, so feel free to talk to us on our <a className="text-success font-weight-bold" href="https://discordapp.com/invite/Terasology">
The following content doesn't go along with the History header, better have something actually of how Terasology was born, the following [wiki page](https://github.com/MovingBlocks/Terasology/wiki/What-is-Terasology) might help you.

2019-10-10 06:38 UTC, majordwarf commented on src/components/About/About.jsx
> +            <div className="mod_bg"></div>
I see you're using CSS background properties for the images to be displayed. It'd be better if we use `Img` component from `gatsby-image` package for better image processing and accessibility. Also I saw you are using Minecraft images/screenshots besides the information. It'd be better if you switch the images accordingly and remove the minecraft images. Same goes for other two images linked. 

Also I tired resizing the screen and it had problem when the screen size fell below 768px, switching to `Img` tag along with some media queries might help. Have a look at the `templates/post.jsx` to see how currently we are handling images.

2019-10-10 06:38 UTC, majordwarf commented on src/components/About/About.css
> +}
It's a good practice to add a newline at the end of the file More about it [here](https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file).

TL;DR - Just add an empty line at end of the file.

2019-10-10 06:38 UTC, majordwarf commented on src/components/About/About.css
> +  background-position: right;
```suggestion
  background-position: right;
  border-radius: 5px;
```

Minor edit to maintain a normalized styling throughout the website.

2019-10-10 06:38 UTC, majordwarf commented on src/components/About/About.css
> +  padding-top: 2rem;
```suggestion
  padding-top: 2rem;
  border-radius: inherit;
```
Follow up from the above message.

2019-10-10 08:36 UTC, GraceChiamaka commented
@majordwarf All your comments have been noted and will be implemented
Thanks

2019-10-16 08:38 UTC, majordwarf commented
@GraceChiamaka Are you still working on the issue?

2019-10-16 20:05 UTC, GraceChiamaka commented
@majordwarf Yes I am.

2019-10-23 13:35 UTC, majordwarf commented
@GraceChiamaka The images still needs to be changed in the History, Modding API and Community section, they still show minecraft images.

2019-10-23 14:50 UTC, GraceChiamaka commented
@majordwarf Yes I am still working on changing those using gatsby-image

2019-10-27 20:56 UTC, GraceChiamaka commented
@majordwarf I've attached screenshots of what the page looks like on desktop and mobile view here
Thanks
![Screenhot_1 The Game](https://user-images.githubusercontent.com/21095670/67641693-615a3d00-f904-11e9-886b-fdf3df6803c0.png)
![Screenshot_2 mobile](https://user-images.githubusercontent.com/21095670/67641694-61f2d380-f904-11e9-955d-1c9558697b5a.png)

2019-10-30 12:55 UTC, majordwarf approved these changes
Great! Thanks for the PR and implementing the changes requested.

2019-10-30 12:57 UTC, merged