fix: active link on navbar
MovingBlocks/movingblocks.github.com pull request #51
Opened 2021-03-23 19:05 UTC by ryuk156

This commit fixes the issue of active nav link on navbar so that the user
user can easily identify on which page he/she is

Before: 
![image](https://user-images.githubusercontent.com/49101492/112203688-ce2c5080-8c38-11eb-9c87-ccc90410fabe.png)

After:
![image](https://user-images.githubusercontent.com/49101492/112203604-bbb21700-8c38-11eb-84d0-241c4cf5cd73.png)

2021-03-27 17:06 UTC, jdrueckert commented
Wasn't able to build this in gitpod :slightly_frowning_face:

2021-03-27 17:23 UTC, ryuk156 commented
> Wasn't able to build this in gitpod :slightly_frowning_face: 

Will let you know 🤔

2021-03-27 18:31 UTC, ryuk156 commented
Updated the PR Please have a look again

2021-04-24 19:35 UTC, jdrueckert requested changes
While we're at the navbar, I'd suggest to switch the modules and forum items

2021-04-24 19:35 UTC, jdrueckert commented on src/components/Header/Header.jsx
> +                  }}
This seems to me linke something you could extract into some kind of class?

2021-04-25 07:05 UTC, ryuk156 commented
> While we're at the navbar, I'd suggest to switch the modules and forum items

done

2021-04-25 07:26 UTC, ryuk156 commented
Updated the PR please have a look

2021-05-14 18:48 UTC, jdrueckert approved these changes

2021-05-14 18:49 UTC, merged